apiVersion: ENC[AES256_GCM,data:kwE=,iv:effKwc8czx1fjiQCqLGrmmKMchpFosU5KZzhky+hvn0=,tag:4I6CyRbAN2sIQgiQnd1yTw==,type:str]
kind: ENC[AES256_GCM,data:1PfFmrqy,iv:7VvDJMcY7rEKge1TxXeeR1f9H903Mkk9nYzmRnd8Z+E=,tag:Nqi16KHpWXmWabHmbQniSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TVNSQ4slErw=,iv:z0ZXsCrUgkja+nIpQUXpbAgkP0D22G6Xp0mpn4VTKeI=,tag:+0ulMBmfvKurK98lmYMN8A==,type:str]
type: ENC[AES256_GCM,data:eqvuAAW3,iv:X1Id92MX/bG3VUvgCt3PzPDAkx+XLwftkAcG3K4CX3g=,tag:NCBrQmMAQU93LV4ZXUyOag==,type:str]
data:
    username: ENC[AES256_GCM,data:Bx3HeZY2w95HTEYP,iv:setehTxYxgO4+R8+Nm3rMU90cU3Szok9VDcAUdA+8EA=,tag:7pU086lN9fG7U1liW0pLaA==,type:str]
    password: ENC[AES256_GCM,data:ncBqAzi6s4g5kAwPcMtJ5NNfopR0u0fmyOVnIeXSvumQUDYv0+E4ZRfJJLs1R5o5ugvvLgHXwpBTezMeZnT+qHYffikeWbAC7yGaFkFdM2kqzUQrCwINYQ==,iv:fdC/2AM4Nz/DBz2kRTGBtU3cDWALgXmqc4Lmwxls+NU=,tag:0sH+RMa/7EDah1GTSRJfZg==,type:str]
    dbname: ENC[AES256_GCM,data:1CtmjJAnLhs=,iv:5VVxeUDodQSqPbB99DrsZltUWs4S4nJRSGRGmgWHhWM=,tag:IM/j2bQdPfPjGkLQUopgIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-23T22:14:25Z"
    mac: ENC[AES256_GCM,data:Ya5zODdYRUJLUSto8k2nmYUM1uYl7LCiRYkK1UznHY5IhNuNHpG40GGRRQFJMWMcDiIzjyu508qQ5ZLmlR4WXKchisBsd/bwjmFCC9i0VjnOVTU+0dYv9tCNStaYYLuiS832T6zFncZRI/93H+L0xXUU9esmwRETNSX8i8hv9Zg=,iv:dTu35/set2O4EgxVqvWhdoLtviDu/kxAJQnpfFR+3V8=,tag:hek8VwoqateVJ2y9xdyLnw==,type:str]
    pgp:
        - created_at: "2023-05-23T22:14:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DjFbMHmgM3h8SAQdASNdtYoUwR4KcbZIMbfYdmsewyhmiQtW4C9Mn98yJWW4w
            LwYb36C9zwHrrXXfQpWQGtGgAZQcIOQ8p26XeTq7wvO3LHfvCOySXjAhOCq/a2pk
            1GYBCQIQgqkczZpLfoSbU03woSSsWaXQHj7jFL1eOuFFOWD7BIKBqutP6s0ClaQj
            SFPdebIRmuswgW0tRp2YyPXcsn3MGx5Pux2mapRktSvj0tRk7anC8r2vJD45Zqc0
            zMYh6+tRfQw=
            =pbNs
            -----END PGP MESSAGE-----
          fp: 533F8603B65864DBD204BDE2F4BB714A72C0C342
    unencrypted_suffix: _unencrypted
    version: 3.7.3
