apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gtdapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: route-master
            port:
              number: 8081 # route-master
