# BackBalancer
apiVersion: v1
kind: Service
metadata:
  name: back-balancer
spec:
  selector:
    app: back-balancer
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: inbox
spec:
  selector:
    app: inbox
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
    - name: health
      protocol: TCP
      port: 8880
---
apiVersion: v1
kind: Service
metadata:
  name: inbox-db
spec:
  selector:
    app: inbox-db
  ports:
    - protocol: TCP
      port: 5432

