# BackBalancer
apiVersion: v1
kind: Service
metadata:
  name: back-balancer
spec:
  selector:
    app: back-balancer
  ports:
    - name: web
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: inbox
spec:
  selector:
    app: inbox
  ports:
    - protocol: TCP
      port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: inbox-db
spec:
  selector:
    app: inbox-db
  ports:
    - protocol: TCP
      port: 5432

